title: Site
unlisted: true

tabs:

  tab_site:
    label: Content
    columns:
      - 1/1:
        sections:

          meta:
            type: fields
            fields:

              menuItems:
                type: structure
                label: Menu items
                fields:
                  menuPage:
                    width: 1/3
                    type: pages
                    min: 1
                    max: 1
                    translate: false
                  menuTextEn:
                    label: Text EN
                    width: 1/3
                    type: text
                    translate: false
                  menuTextDe:
                    label: Text DE
                    width: 1/3
                    type: text
                    translate: false

          pages:
            type: pages
            create:
              - bubble
              - container

              # cookieBanner:
              #   label: Cookie banner text
              #   type: textarea
              #   width: 1/2
              
  tab_settings:
    label: Site settings
    columns:
      - 1/1:
        sections:

          meta2:
            type: fields
            fields:

              bgImages:
                label: Background images
                type: files
                min: 1
                translate: false
                info: "{{ file.active.bool2Text('on ✨', 'off ☁️') }}"
                uploads:
                  template: bgs

              footerText:
                type: text
              
              socialDescription:
                type: textarea
                width: 1/2
              
              socialImage:
                type: files
                min: 1
                max: 1
                help: "Un'immagine di 1200x630 px"
                width: 1/2
                translate: false
              
  tab_sessions21:
    label: Sessions 21
    columns:
      - 1/1:
        sections:

          tab_sessions21_fields:
            type: fields
            fields:

              sessions21_tags:
                label: "Tags (language: {{kirby.language.code}})"
                type: structure
                fields:
                  s21Text:
                    label: Text to search
                    type: text
